steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_API_URL=https://geonews-api-4loazyhcxa-uc.a.run.app
      - --build-arg
      - VITE_WS_URL=wss://geonews-websocket-4loazyhcxa-uc.a.run.app/ws
      - --build-arg
      - VITE_MAPBOX_TOKEN=$$MAPBOX_TOKEN
      - -t
      - us-central1-docker.pkg.dev/lab2-485303/geonews/frontend:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/lab2-485303/geonews/frontend:latest
      - .
    secretEnv: [MAPBOX_TOKEN]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - geonews-frontend
      - --image
      - us-central1-docker.pkg.dev/lab2-485303/geonews/frontend:$COMMIT_SHA
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --min-instances
      - "0"
      - --max-instances
      - "3"

availableSecrets:
  secretManager:
    - versionName: projects/lab2-485303/secrets/MAPBOX_TOKEN/versions/latest
      env: MAPBOX_TOKEN

images:
  - us-central1-docker.pkg.dev/lab2-485303/geonews/frontend:$COMMIT_SHA
  - us-central1-docker.pkg.dev/lab2-485303/geonews/frontend:latest
