// Mock articles used during frontend development before the backend is wired up.
// Each article has a lat/lng so it renders as a dot on the globe.

export const MOCK_ARTICLES = [
  {
    article_id: '1',
    title: 'US Senate passes new AI regulation bill',
    category: 'Politics',
    lat: 38.9,
    lng: -77.0,
    published_at: '2025-03-01T10:00:00Z',
    image_url: null,
  },
  {
    article_id: '2',
    title: 'OpenAI releases GPT-5 with multimodal reasoning',
    category: 'AI',
    lat: 37.7,
    lng: -122.4,
    published_at: '2025-03-02T08:00:00Z',
    image_url: null,
  },
  {
    article_id: '3',
    title: 'European Central Bank cuts interest rates',
    category: 'Finance',
    lat: 50.1,
    lng: 8.6,
    published_at: '2025-03-03T09:00:00Z',
    image_url: null,
  },
  {
    article_id: '4',
    title: 'India launches new space mission to Mars',
    category: 'Technology',
    lat: 13.0,
    lng: 80.2,
    published_at: '2025-03-04T06:00:00Z',
    image_url: null,
  },
  {
    article_id: '5',
    title: 'WHO warns of new respiratory virus outbreak',
    category: 'Health',
    lat: 31.2,
    lng: 121.4,
    published_at: '2025-03-05T07:00:00Z',
    image_url: null,
  },
  {
    article_id: '6',
    title: 'Champions League final set for London',
    category: 'Sports',
    lat: 51.5,
    lng: -0.1,
    published_at: '2025-03-06T18:00:00Z',
    image_url: null,
  },
  {
    article_id: '7',
    title: 'Netflix announces record subscriber growth',
    category: 'Entertainment',
    lat: 34.0,
    lng: -118.2,
    published_at: '2025-03-07T15:00:00Z',
    image_url: null,
  },
  {
    article_id: '8',
    title: 'Brazil Amazon deforestation hits record low',
    category: 'Politics',
    lat: -15.7,
    lng: -47.9,
    published_at: '2025-03-08T11:00:00Z',
    image_url: null,
  },
  {
    article_id: '9',
    title: 'Tokyo startup raises $500M for humanoid robots',
    category: 'Technology',
    lat: 35.6,
    lng: 139.6,
    published_at: '2025-03-09T04:00:00Z',
    image_url: null,
  },
  {
    article_id: '10',
    title: 'South Africa hosts G20 climate summit',
    category: 'Politics',
    lat: -25.7,
    lng: 28.2,
    published_at: '2025-03-10T09:00:00Z',
    image_url: null,
  },
]
